name: Feedback (CommentHQ Framework)
description: Propose an improvement or report an issue in the framework
title: "[Feedback]: "
labels: ["feedback"]
body:
  - type: dropdown
    id: type
    attributes:
      label: Type
      options: [ISSUE, IMPROVEMENT, QUESTION, DECISION]
    validations:
      required: true
  - type: input
    id: title
    attributes:
      label: Short title
      placeholder: e.g., Pin Node version in QoS workflow
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: What happened / what you want; context/links; expected vs actual (if ISSUE)
  - type: dropdown
    id: impact
    attributes:
      label: Impact
      options: [High, Medium, Low]
  - type: dropdown
    id: category
    attributes:
      label: Category
      options: [Build QoS, Repo Sync, UI Enhancements, CI/CD, Policy, Other]
  - type: dropdown
    id: status
    attributes:
      label: Initial Status
      options: [Pending, Implemented, Deferred, Rejected]
    validations:
      required: true
