name: Build BundleMe GUI (portable EXE)

on:
  workflow_dispatch:
  push:
    paths:
      - "tools/bundleme-gui/**"
      - ".github/workflows/build-bundleme.yml"

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
        working-directory: tools/bundleme-gui

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: tools/bundleme-gui/package-lock.json

      - name: Install deps (CI)
        run: |
          if (!(Test-Path package-lock.json)) { npm install }
          npm ci

      - name: Build portable EXE
        run: |
          npm run dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BundleMe-GUI
          path: tools/bundleme-gui/dist/*