name: Make Repo Private (manual)

on:
  workflow_dispatch:

permissions:
  contents: write
  administration: write

jobs:
  toggle:
    runs-on: ubuntu-latest
    steps:
      - name: Make private
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.REPO_ADMIN_TOKEN }}
          script: |
            await github.rest.repos.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              private: true
            });
