name: Build CommentHQ BundleMe GUI

on:
  push:
    tags:
      - 'gui-v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20 LTS (CI-stable)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            CommentHQ-BundleMe-GUI/package-lock.json

      - name: Assert lockfile present
        run: |
          if (!(Test-Path 'CommentHQ-BundleMe-GUI/package-lock.json')) {
            Write-Error 'Missing lockfile: CommentHQ-BundleMe-GUI/package-lock.json'
          }

      - name: Install deps
        working-directory: CommentHQ-BundleMe-GUI
        run: npm ci

      - name: Build portable exe
        working-directory: CommentHQ-BundleMe-GUI
        run: npm run build:portable

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CommentHQ-BundleMe-GUI-portable
          path: CommentHQ-BundleMe-GUI/dist/*.exe

      - name: Release (on tag)
        if: startsWith(github.ref, 'refs/tags/gui-v')
        uses: softprops/action-gh-release@v2
        with:
          files: CommentHQ-BundleMe-GUI/dist/*.exe
