name: Build BundleMe GUI (portable)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "tools/bundleme-gui/**"
      - ".github/workflows/build-bundleme-gui.yml"

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
        working-directory: tools/bundleme-gui

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (no cache)
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm install

      - name: Build portable EXE
        run: npx electron-builder --win portable --publish never

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CommentHQ-BundleMe-GUI
          path: dist/*.exe
          if-no-files-found: error
