name: Build BundleMe GUI (portable)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "tools/bundleme-gui/**"
      - ".github/workflows/build-bundleme-gui.yml"

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
        working-directory: tools/bundleme-gui

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Safe npm cache (only if it exists)
      - name: Get npm cache dir
        id: npm-cache
        run: |
          $dir = npm config get cache
          echo "dir=$dir" >> $env:GITHUB_OUTPUT

      - name: Ensure npm cache dir exists
        run: |
          New-Item -ItemType Directory -Force -Path "${{ steps.npm-cache.outputs.dir }}" | Out-Null

      - name: Cache npm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('tools/bundleme-gui/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install deps (lockfile if present)
        run: |
          if (Test-Path package-lock.json) { npm ci } else { npm install }

      - name: Print electron-builder version
        run: npx electron-builder --version

      - name: Build portable EXE
        run: npm run build:win
        env:
          CI: "true"

      - name: Show dist tree (debug)
        run: |
          if (Test-Path dist) {
            Write-Host "== DIST TREE =="
            Get-ChildItem -Recurse dist | Format-Table -AutoSize
          } else {
            Write-Error "dist/ does not exist (build likely failed)."
          }

      - name: Find built EXE path
        id: findexe
        run: |
          $exe = Get-ChildItem -Path dist -Recurse -Filter *.exe -ErrorAction SilentlyContinue | Select-Object -First 1
          if (-not $exe) {
            Write-Error "No .exe found under dist/. Check the previous step's tree and build logs."
            exit 1
          }
          Write-Host "Found:" $exe.FullName
          "exePath=$($exe.FullName)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8

      - name: Upload GUI Executable
        uses: actions/upload-artifact@v4
        with:
          name: CommentHQ-BundleMe-GUI
          path: ${{ steps.findexe.outputs.exePath }}
          if-no-files-found: error
