name: Build BundleMe GUI (portable)
on:
  workflow_dispatch:        # manual only (prevents dummy runs)
jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
        working-directory: tools/bundleme-gui
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Ensure lockfile
        run: |
          if (-not (Test-Path package-lock.json)) {
            npm install --package-lock-only --no-audit --no-fund
          }
      - name: Install deps
        run: npm ci --no-audit --no-fund
      - name: Build portable
        run: npm run build:win
      - name: Verify & list dist
        run: |
          if (-not (Test-Path dist)) { throw "dist/ not created" }
          $exe = Get-ChildItem -Path dist -Filter *.exe -ErrorAction SilentlyContinue
          if (-not $exe) { throw "No .exe in dist/" }
          Get-ChildItem -Force dist
      - uses: actions/upload-artifact@v4
        with:
          name: CommentHQ-BundleMe-GUI
          path: tools/bundleme-gui/dist/*.exe
          if-no-files-found: error
