name: Build CommentHQ (single EXE)

on:
  workflow_dispatch: {}

jobs:
  build-win:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build portable exe
        run: npx electron-builder --win portable --config electron-builder.yml

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: commenthq-win64
          path: app/dist/**
