# .github/workflows/build-bundleme-gui.yml
name: Build BundleMe GUI

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/build-bundleme-gui.yml'
      - 'tools/bundleme-gui/**'

jobs:
  build-win:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
        working-directory: tools/bundleme-gui

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # tiny sanity check so we fail early if JSON is broken again
      - name: Validate package.json
        run: node -e "JSON.parse(require('fs').readFileSync('package.json','utf8')); console.log('package.json OK');"

      - name: Install deps
        run: |
          if (Test-Path package-lock.json) { npm ci } else { npm i && npm i --package-lock-only }

      - name: Build portable exe
        run: npm run build:win:portable

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BundleMe-GUI-win-portable
          path: dist/*.exe
          if-no-files-found: error
