name: Build CommentHQ — Minimal Pinned

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/build-commenthq-minimal-pinned.yml"
      - "package.json"
      - "package-lock.json"
      - "src-tauri/**"
      - "app/**"

permissions:
  contents: read

env:
  NODE_VERSION: "20.19.4"

jobs:
  build-windows:
    runs-on: windows-2022
    timeout-minutes: 35

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Install NSIS (for Windows bundling)
        shell: pwsh
        run: |
          choco install nsis -y
          $env:Path = "$env:ProgramFiles\NSIS;$env:Path"

      # ---------- Inline guard: no external files required ----------
      - name: GUI Ready Check (inline)
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          function Fail($m){ Write-Host "::error:: $m"; throw $m }
          if (!(Test-Path package.json)) { Fail "package.json missing at repo root." }
          if (!(Test-Path package-lock.json)) { Fail "package-lock.json missing (required for npm ci)." }
          if (!(Test-Path src-tauri/tauri.conf.json)) { Fail "src-tauri/tauri.conf.json missing." }
          if (!(Test-Path tools/bundleme-gui)) { Write-Host "::warning:: tools/bundleme-gui not found (not fatal)." }
          Write-Host "GUI_READY = TRUE"

      # ---------- Deterministic installs (root + optional app/) ----------
      - name: Install JS deps (deterministic)
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          if (Test-Path package-lock.json) { npm ci } else { Write-Host "::warning:: No root package-lock.json" }
          if (Test-Path app/package.json) {
            if (Test-Path app/package-lock.json) { npm ci --prefix app } else { Write-Host "::warning:: app/package-lock.json missing" }
          }

      # ---------- Self-healing frontend build (root or app/) ----------
      - name: Build frontend
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          function TryRun($cmd){
            Write-Host ">> $cmd"
            cmd /c $cmd
            if ($LASTEXITCODE -ne 0) { Write-Host "::warning:: command failed: $cmd (code $LASTEXITCODE)" }
            return $LASTEXITCODE
          }
          $code = 1
          if (Test-Path package.json) { $code = TryRun "npm run build" }
          if ($code -ne 0 -and (Test-Path app/package.json)) { $code = TryRun "npm run build --prefix app" }
          if ($code -ne 0) { throw "No usable build script found at root or app/. Add one or adjust this step." }

      # ---------- Verify dist exists (common locations) ----------
      - name: Verify dist exists
        id: distcheck
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $candidates = @("dist","app/dist","packages/app/dist")
          $found = $null
          foreach ($c in $candidates) {
            if (Test-Path $c) { $found = $c; break }
          }
          if (-not $found) {
            throw "Frontend dist folder not found. Ensure your build outputs to one of: dist, app/dist, packages/app/dist; or update src-tauri/tauri.conf.json build.distDir accordingly."
          }
          Write-Host "Using dist at $found"
          "dist=$found" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding ascii

      # ---------- Tauri build ----------
      - name: Build Tauri (Windows)
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: "."
          args: "--target x86_64-pc-windows-msvc"

      # ---------- Locate bundle ----------
      - name: Locate bundle
        id: collect
        shell: pwsh
        run: |
          $bundle = Join-Path "src-tauri" "target\release\bundle"
          if (!(Test-Path $bundle)) {
            Write-Error "Expected bundle directory not found at $bundle"
          }
          Write-Host "Bundle path: $bundle"
          "bundle=$bundle" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding ascii

      # ---------- Inline SHA256 ----------
      - name: Generate SHA256.json (inline)
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $in = "${{ steps.collect.outputs.bundle }}"
          if (!(Test-Path $in)) { throw "InputDir not found: $in" }
          $hashes = @()
          Get-ChildItem -Path $in -Recurse -File | ForEach-Object {
            $h = Get-FileHash -Algorithm SHA256 -Path $_.FullName
            $hashes += [pscustomobject]@{ file = $_.FullName; sha256 = $h.Hash.ToLower() }
          }
          $hashes | ConvertTo-Json -Depth 3 | Out-File -FilePath "SHA256.json" -Encoding utf8
          Write-Host "Wrote SHA256.json with $($hashes.Count) entries."

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CommentHQ-windows-build
          path: |
            ${{ steps.collect.outputs.bundle }}/**
            SHA256.json
          if-no-files-found: error
