- name: GUI Ready Check (inline)
  shell: pwsh
  run: |
    $ErrorActionPreference = 'Stop'
    function Fail($m){ Write-Host "::error:: $m"; throw $m }
    if (!(Test-Path package.json)) { Fail "package.json missing at repo root." }
    if (!(Test-Path package-lock.json)) { Fail "package-lock.json missing (required for npm ci)." }
    if (!(Test-Path src-tauri/tauri.conf.json)) { Fail "src-tauri/tauri.conf.json missing." }
    if (!(Test-Path tools/bundleme-gui)) { Write-Host "::warning:: tools/bundleme-gui not found (not fatal)." }
    Write-Host "GUI_READY = TRUE"
