name: CommentHQ Portable (CI Live — QoS)

on:
  workflow_dispatch:
  push:
    tags: ['v*.*.*']

jobs:
  win-portable:
    runs-on: windows-2022
    defaults:
      run:
        shell: pwsh
        working-directory: tools/bundleme-gui

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node (pinned)
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.4'
          cache: npm
          cache-dependency-path: tools/bundleme-gui/package-lock.json

      - name: Ensure lockfile (deterministic)
        run: |
          if (-not (Test-Path package-lock.json)) {
            npm install --package-lock-only --no-audit --no-fund
          }

      - name: Install deps (ci)
        run: npm ci --no-audit --no-fund

      - name: Smoke — package.json loads
        run: node -e "require('./package.json'); console.log('package.json OK')"

      - name: Show electron-builder version
        run: npx electron-builder --version

      - name: Build EXE (portable)
        env:
          DEBUG: electron-builder
        run: npm run build:win

      - name: Verify dist and list
        run: |
          if (-not (Test-Path dist)) { throw 'dist/ not created' }
          $exe = Get-ChildItem -Path dist -Filter *.exe -ErrorAction SilentlyContinue
          if (-not $exe) {
            Write-Host "No EXE produced. Dist contents:"
            if (Test-Path dist) { Get-ChildItem -Recurse dist | Format-List }
            throw "No .exe in dist/"
          }
          Get-ChildItem -Force dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CommentHQ-BundleMe-GUI
          path: tools/bundleme-gui/dist/*.exe
          if-no-files-found: error

      - name: Release on tag
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: tools/bundleme-gui/dist/*.exe
          generate_release_notes: true
