name: Toggle Repo Visibility
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Make repo public or private'
        required: true
        default: 'private'
        type: choice
        options:
          - public
          - private

jobs:
  toggle:
    runs-on: ubuntu-latest
    steps:
      - name: Toggle visibility
        run: |
          echo "Toggling repo visibility to {{ github.event.inputs.action }}"
          gh repo edit {{ github.repository }} --visibility {{ github.event.inputs.action }}